### ISSUE TITLE
process.EventEmitter is going to be removed in Node.js 7, use require('events')

### ISSUE THREAD

**Issue by ChALkeR** [3rd-Eden/FlashPolicyFileServer#9]
`process.EventEmitter` was deprecated in Node.js 6 and is going to be removed in Node.js 7, use `require('events')` as a drop-in replacement.

Refs: https://github.com/nodejs/node/pull/5049, https://github.com/nodejs/node/pull/6862.

Used on [lib/server.js#L253](https://github.com/3rd-Eden/FlashPolicyFileServer/blob/master/lib/server.js#L253) and in tests.

**Comment by jvilk** [comment]
+1. Please fix this. This library no longer functions in Node 7, which prevents other libraries -- like websockify -- from working.

**Comment by BrianLenzo** [comment]
This is now completely broken with Node 7.

**Comment by 3rd-Eden** [comment]
Published 0.0.6 with a fix, apologies for the inconvenience this caused.
